allowBuilds:
  ' ': true
  '-': true
  /: true
  '@': true
  a: true
  b: true
  c: true
  d: true
  e: true
  h: true
  i: true
  j: true
  l: true
  o: true
  p: true
  r: true
  s: true
  t: true
  u: true
  w: true
